name: dalel
description: "A New Figma Design I Want  To Implement"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # firebase
  firebase_core: 2.15.1
  firebase_auth: 4.7.3

  # local storage
  shared_preferences: 2.1.0
  hive: 2.2.3
  hive_flutter: 1.1.0

  # state management
  bloc: 8.1.0
  flutter_bloc: 8.1.1
  equatable: 2.0.5

  # for making the splash screen
  flutter_native_splash: 2.3.10




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Heebo
       fonts:
         - asset: assets/fonts/heebo/Heebo-Bold.ttf
         - asset: assets/fonts/heebo/Heebo-Medium.ttf
         - asset: assets/fonts/heebo/Heebo-Regular.ttf
     - family: Poppins
       fonts:
         - asset: assets/fonts/poppin/Poppins-Bold.ttf
         - asset: assets/fonts/poppin/Poppins-Medium.ttf
         - asset: assets/fonts/poppin/Poppins-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_assets:
  assets_path: assets/images/
  output_path: lib/utils
  filename: assets.dart